# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn <- function(train, group, test, kn, disttype) {
    .Call('otoclass_knn', PACKAGE = 'otoclass', train, group, test, kn, disttype)
}

